'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''
import os

def fib(n):
	if n == 0 or n == 1:
		return 1
	return fib(n - 1) + fib(n - 2)

n = 0
f = 0
sum_ = 0
a = 4000000 / 100
b = 0
while f < 4000000:
	f = fib(n)
	if f % 2 == 0:
		sum_ += f
	n += 1
	if f > a * b:
		os.system('cls')
		print('{}%'.format(b))
		b = f // 40000

os.system('cls')
print('100%')

print('Sum is {}'.format(sum_))
input()
